Repository team-aie/app, pull requests merged in 2021-03, with the labels that each got.

#93 fix: fix alerts reported by LGTM.com checks
  README.md
  src/renderer/utils/line-by-line-parser.ts
  webpack.license.config.js
Labels: enhancement, javascript

#94 build: use commit hooks and prettier to enforce Markdown file formatting
  .husky/.gitignore
  .husky/pre-commit
  .prettierrc.js
  .vscode/extensions.json
  .vscode/settings.json
  README.md
  external/delta_eng_ver5/README.md
  lint-staged.config.js
  package-lock.json
  package.json
Labels: documentation, enhancement

#95 refactor: deprecate electron's built-in remote module
  package-lock.json
  package.json
  src/common/electron-remote.d.ts
  src/main/index.ts
  src/renderer/components/configure-recording-set-page/configure-recording-set-page.test.tsx
  src/renderer/components/license-disclosure/index.tsx
  src/renderer/utils/fs-utils.test.ts
  src/renderer/utils/fs-utils.ts
  src/renderer/utils/media-utils.ts
Labels: enhancement, javascript

#96 feat: make app window hide rather than close to preserve app state
  src/common/errors.ts
  src/main/index.ts
Labels: enhancement, javascript, mac

#98 build: add linter rules and enforce linting on code comments
  .eslintignore
  .eslintrc.js
  src/main/index.ts
  src/renderer/aie-app.tsx
  src/renderer/components/configure-recording-set-page/preview-page.tsx
  src/renderer/components/configure-recording-set-page/types.ts
  src/renderer/components/open-project-page/known-projects.ts
  src/renderer/components/recording-page/recording-visualization.tsx
  src/renderer/contexts/locale-context.ts
  src/renderer/licenses.ts.base
  src/renderer/services/i18n/index.ts
  src/renderer/services/i18n/webpack-import-backend.ts
  src/renderer/utils/file-monitor.tsx
  src/renderer/utils/media-utils.ts
  webpack.license.config.js
Labels: enhancement

#101 feat: upgrade Electron major version to 12
  package-lock.json
  package.json
Labels: enhancement

#103 fix: add missing translations in the audio settings page and list previews
  src/locales/en-US/translation.json
  src/locales/ja-JP/translation.json
  src/locales/zh-CN/translation.json
  src/renderer/components/configure-recording-set-page/configure-recording-set-page.tsx
  src/renderer/components/settings-page/index.tsx
Labels: bug, linux, mac, windows

#119 build: remove fast package step because production package is always run
  .github/workflows/cicd.yml
  electron-builder.js
Labels: enhancement

#122 fix: correct the notification title on Windows
  src/main/index.ts
Labels: enhancement, windows

#92 feat: allow users to resume from where they left off in a project
  package-lock.json
  src/common/env-and-consts.ts
  src/locales/en-US/translation.json
  src/locales/ja-JP/translation.json
  src/locales/zh-CN/translation.json
  src/main/index.ts
  src/renderer/components/aie-app/aie-app.tsx
  src/renderer/components/open-project-page/open-project-page.tsx
Labels: enhancement, linux, mac, windows
